
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.sql.PreparedStatement;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.TableRowSorter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rossy
 */
public class LibraryManagement extends javax.swing.JFrame {

    /**
     * Creates new form LibraryManagement
     */
    public Connection conn;
    public Statement ps1;
    public PreparedStatement ps;
    public ResultSet rs;
    public DefaultTableModel t;
    public Connect c = new Connect();
    int id;
    String title;
    String firstName;
    String lastName;
    int publishedYear;
    String genre;
    public String[] selectedValue;
    public LibraryManagement() {
        initComponents();
        try {
            conn = DriverManager.getConnection("jdbc:sqlite:librarydb.db");
        } catch (SQLException ex) {
            Logger.getLogger(LibraryManagement.class.getName()).log(Level.SEVERE, null, ex);
        }
        t = (DefaultTableModel) jTableBooks.getModel();
        tableRefresh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldId = new javax.swing.JTextField();
        jLabelId = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jTextFieldTitle = new javax.swing.JTextField();
        jLabelFirstName = new javax.swing.JLabel();
        jTextFieldFirstName = new javax.swing.JTextField();
        jLabelLastName = new javax.swing.JLabel();
        jTextFieldLastName = new javax.swing.JTextField();
        jLabelYear = new javax.swing.JLabel();
        jTextFieldYear = new javax.swing.JTextField();
        jLabelGenre = new javax.swing.JLabel();
        jTextFieldGenre = new javax.swing.JTextField();
        jButtonAdd = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableBooks = new javax.swing.JTable();
        jTextFieldSearch = new javax.swing.JTextField();
        jLabelSearch = new javax.swing.JLabel();
        jButtonSearch = new javax.swing.JButton();
        jRadioButtonAsc = new javax.swing.JRadioButton();
        jRadioButtonDesc = new javax.swing.JRadioButton();
        jLabelFilter = new javax.swing.JLabel();
        jButtonRefresh = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(376, 315));

        jTextFieldId.setPreferredSize(new java.awt.Dimension(166, 224));

        jLabelId.setText("ID:");

        jLabelTitle.setText("Title:");

        jTextFieldTitle.setPreferredSize(new java.awt.Dimension(164, 24));

        jLabelFirstName.setText("Author First Name:");

        jTextFieldFirstName.setPreferredSize(new java.awt.Dimension(164, 24));

        jLabelLastName.setText("Author Last Name:");

        jTextFieldLastName.setMinimumSize(new java.awt.Dimension(64, 30));
        jTextFieldLastName.setPreferredSize(new java.awt.Dimension(164, 24));

        jLabelYear.setText("Year:");

        jTextFieldYear.setPreferredSize(new java.awt.Dimension(164, 24));

        jLabelGenre.setText("Genre:");

        jTextFieldGenre.setPreferredSize(new java.awt.Dimension(164, 24));

        jButtonAdd.setText("Add");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelLastName))
                            .addComponent(jLabelYear, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addComponent(jLabelGenre))
                    .addComponent(jLabelFirstName)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelTitle)
                            .addComponent(jLabelId)))
                    .addComponent(jButtonAdd, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldLastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(2, 2, 2)))
                        .addGap(26, 26, 26))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jButtonUpdate)
                        .addGap(35, 35, 35)
                        .addComponent(jButtonDelete)
                        .addContainerGap(58, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelId)
                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTitle))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelFirstName)
                    .addComponent(jTextFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLastName)
                    .addComponent(jTextFieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldYear, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelYear))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelGenre))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDelete)
                    .addComponent(jButtonUpdate)
                    .addComponent(jButtonAdd))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextFieldTitle.getAccessibleContext().setAccessibleName("");

        jTableBooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Title", "Author First Name", "Author Last Name", "Year", "Genre"
            }
        ));
        jTableBooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableBooksMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableBooks);

        jLabelSearch.setText("Search:");

        jButtonSearch.setText("Search");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        jRadioButtonAsc.setText("Asc");
        jRadioButtonAsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAscActionPerformed(evt);
            }
        });

        jRadioButtonDesc.setText("Desc");
        jRadioButtonDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDescActionPerformed(evt);
            }
        });

        jLabelFilter.setText("Filter table:");

        jButtonRefresh.setText("Refresh Table");
        jButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshActionPerformed(evt);
            }
        });
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonRefresh)
                .addGap(41, 41, 41)
                .addComponent(jLabelSearch)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSearch)
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButtonAsc)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonDesc))
                    .addComponent(jLabelFilter))
                .addGap(92, 92, 92))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFilter)
                    .addComponent(jButtonSearch)
                    .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSearch)
                    .addComponent(jButtonRefresh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonAsc)
                    .addComponent(jRadioButtonDesc))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE))
                .addGap(66, 66, 66))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableBooksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableBooksMouseClicked
        // TODO add your handling code here:
        int selectedRowIndex = jTableBooks.getSelectedRow();
        
        if (selectedRowIndex >= 0) {
            TableModel model = jTableBooks.getModel();
            jTextFieldId.setText(model.getValueAt(selectedRowIndex, 0).toString());
            jTextFieldTitle.setText(model.getValueAt(selectedRowIndex, 1).toString());
            jTextFieldFirstName.setText(model.getValueAt(selectedRowIndex, 2).toString());
            jTextFieldLastName.setText(model.getValueAt(selectedRowIndex, 3).toString());
            jTextFieldYear.setText(model.getValueAt(selectedRowIndex, 4).toString());
            jTextFieldGenre.setText(model.getValueAt(selectedRowIndex, 5).toString());
            
            id = Integer.parseInt(model.getValueAt(selectedRowIndex, 0).toString());
            title = model.getValueAt(selectedRowIndex, 1).toString();
            firstName = model.getValueAt(selectedRowIndex, 2).toString();
            lastName = model.getValueAt(selectedRowIndex, 3).toString();
            publishedYear = Integer.parseInt(model.getValueAt(selectedRowIndex, 4).toString());
            genre = model.getValueAt(selectedRowIndex, 5).toString();
            
            selectedValue = new String[]{model.getValueAt(selectedRowIndex, 0).toString(),model.getValueAt(selectedRowIndex, 1).toString()
                ,model.getValueAt(selectedRowIndex, 2).toString(),model.getValueAt(selectedRowIndex, 3).toString(),
                model.getValueAt(selectedRowIndex, 4).toString(),model.getValueAt(selectedRowIndex, 5).toString()
        };
        }
    }//GEN-LAST:event_jTableBooksMouseClicked

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // TODO add your handling code here:
        String idField = jTextFieldId.getText();
        String titleField = jTextFieldTitle.getText();
        String firstNameField = jTextFieldFirstName.getText();
        String lastNameField = jTextFieldLastName.getText();
        String yearField = jTextFieldYear.getText();
        String genreField = jTextFieldGenre.getText();
        
        if (!idField.equals(id) || !titleField.equals(title) || !firstNameField.equals(firstName) || !lastNameField.equals(lastName)
                || !yearField.equals(publishedYear) || !genreField.equals(genre)) {
            String[] values = {idField, titleField, firstNameField, lastNameField, yearField, genreField};
            String[] columns = {"Id", "Title", "AuthorFirstName","AuthorLastName","PublishedYear","Genre"};
            
            
            c.update(columns, values, "Id", id, "Books");
        }
        tableRefresh();
        JOptionPane.showMessageDialog(null,"The database was successfully updated!");
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private List<String> validateValues(){
        List<String> errors = new ArrayList();
         try{
           Integer.valueOf(jTextFieldYear.getText());
        }catch(NumberFormatException e){
            errors.add("Невалидни данни, моля въведете година с число.");
        }
        return errors;
    }
    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // TODO add your handling code here:
        List<String> errors = validateValues();
   
        //Този блок ако има грешки ще ти покаже съобщение с грешките
        if(!errors.isEmpty()){
            String errorString = "";
            for(String error:errors)errorString += error.concat(" ");
            JOptionPane.showMessageDialog(null, errorString);
            return;
        }
        Connect connect = new Connect();
        int year = Integer.parseInt(jTextFieldYear.getText());
        String title = jTextFieldTitle.getText();
        String authorFirstName = jTextFieldFirstName.getText();
        String authorLastName = jTextFieldLastName.getText();
        String genre = jTextFieldGenre.getText();
        connect.addBook(title, authorFirstName, authorLastName, genre, year);
        tableRefresh();
        JOptionPane.showMessageDialog(null,"The record was successfully added.");
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        c.delete("Id", Integer.parseInt(selectedValue[0]), "Books");
        tableRefresh();
        jTextFieldTitle.setText("");
        jTextFieldId.setText("");
        jTextFieldFirstName.setText("");
        jTextFieldLastName.setText("");
        jTextFieldYear.setText("");
        jTextFieldGenre.setText("");
        JOptionPane.showMessageDialog(null,"The record was successully deleted.");
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        // TODO add your handling code here:
        String[] columnsArray = {"Id", "Title", "AuthorFirstName","AuthorLastName","PublishedYear","Genre"};
        String searchValue = jTextFieldSearch.getText();
        String whereValue = "Title";
        
        
        var data = c.selectSearch(columnsArray, "books", searchValue, whereValue);
        DefaultTableModel dtm = (DefaultTableModel) jTableBooks.getModel();
        String dataToString = data.toString();
        String[] values = dataToString.split("---");
        //Object[] objectArray = values.toArray();
        dtm.setRowCount(0);
        dtm.addRow(values);
        
        
    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jRadioButtonAscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAscActionPerformed
        // TODO add your handling code here:
        String sort = "asc";
        sortTable(1, sort);
    }//GEN-LAST:event_jRadioButtonAscActionPerformed

    private void jRadioButtonDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDescActionPerformed
        // TODO add your handling code here:
        String sort = "desc";
        sortTable(1,sort);
        if (jRadioButtonAsc.isSelected()) {
            jRadioButtonAsc.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonDescActionPerformed

    private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshActionPerformed
        // TODO add your handling code here:
        tableRefresh();
    }//GEN-LAST:event_jButtonRefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibraryManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibraryManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibraryManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibraryManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibraryManagement().setVisible(true);
            }
        });
    }
    private void sortTable(int column, String sortOrder) {
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<DefaultTableModel>((DefaultTableModel)jTableBooks.getModel());
        sorter.setSortable(column, true);
        if (sortOrder.equals("asc")) {
            sorter.setSortKeys(java.util.List.of(new RowSorter.SortKey(column, SortOrder.ASCENDING)));
        } else if (sortOrder.equals("desc")) {
            sorter.setSortKeys(java.util.List.of(new RowSorter.SortKey(column, SortOrder.DESCENDING)));
        }
        jTableBooks.setRowSorter(sorter);
    }
    public void tableRefresh(){
        t.setRowCount(0);
        ArrayList<String> e = c.select(new String[]{"Id", 
                                                "Title",    
                                                "AuthorFirstName",
                                                "AuthorLastName",
                                                "PublishedYear",
                                                "Genre"}, "Books");
        for (int i = 0; i < e.size(); i++) {
            String[] row = e.get(i).split("---");
            t.addRow(new Object[] {
                row[0],
                row[1],            
                row[2],
                row[3],
                row[4],
                row[5]
            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabelFilter;
    private javax.swing.JLabel jLabelFirstName;
    private javax.swing.JLabel jLabelGenre;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelLastName;
    private javax.swing.JLabel jLabelSearch;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelYear;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonAsc;
    private javax.swing.JRadioButton jRadioButtonDesc;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableBooks;
    private javax.swing.JTextField jTextFieldFirstName;
    private javax.swing.JTextField jTextFieldGenre;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldLastName;
    private javax.swing.JTextField jTextFieldSearch;
    private javax.swing.JTextField jTextFieldTitle;
    private javax.swing.JTextField jTextFieldYear;
    // End of variables declaration//GEN-END:variables
}
